### PR TITLE
Formatting and link improvements

### PR DESCRIPTION
**Pull request by VibroAxe**
Adjustment to formatting to add the last run trace timing and use --primary-text-color to override the "nasty" link colours. Fixes half of #1

Clicking the automation name opens the edit automation pane, whereas clicking the last run time opens the traces view

### CODE REVIEW

**Comment by VibroAxe** [comment]
@DirkHeinke nice job! Couple of suggested improvements from a day using it

**Comment by VibroAxe** [comment]
Example UI from my install

**Comment by DirkHeinke** [comment]
Nice, any chance you can commit it without the whitespace changes? It's a bit hard to review.

**Comment by VibroAxe** [comment]
> Nice, any chance you can commit it without the whitespace changes? It's a bit hard to review.

Whoops! Copied and pasted out of the code server in HA, completely broke the white spacing! New commits resolve

**Comment by VibroAxe** [comment]
@DirkHeinke also added a simple handler for `<details>` vs `<details open>` to fully resolve #1

**Comment by VibroAxe** [comment]
Thought about this on the walk to lunch and realised a much more elegant solution to summary expansion. `defaultOpenTreeDepth` can now be set to an integer to allow fine control of the expansion depth

0
image

1
image

2
image

**Comment by VibroAxe** [comment]
Apologies, You might want to do this as a squash merge :D

**Review by DirkHeinke — APPROVED** [review]
Thank you very much for your improvements.

**Comment by VibroAxe** [comment]
> Thank you very much for your improvements.

Thank you for the excellent original idea!

**Pull request merged**
